### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by pmoreno1980** [xumulus/magento2-fast-product-images#12]
im getting this error when i tried to run composer require ....

[RuntimeException]
  Failed to execute git clone --mirror 'git@github.com:xumulus/magento2-fast-product-images.git' '/home/yottaa/.composer/cache/vcs/git-github.com-xumulus-
  magento2-fast-product-images.git/'

I am doing something wrong? pleas elet me know

thanks

**Comment by dankoz51** [comment]
This worked for me on git 2.15 , maybe its a local git issue with version or something

**Comment by Dannymx** [comment]
Remove -n flag when executing the composer require command, you might have to create a token to access the repo, that fixed it for me.
