### ISSUE TITLE
Magento 2 Thumbnails not changing on swatch change.

### ISSUE THREAD

**Issue by iroken222** [xumulus/magento2-fast-product-images#5]
Currently we have a site running this extension. When we go to the products page on the site the image loads super fast which is awesome. However on magento 2.2.3 EE we have run into an issue where the thumbnails do not update properly. I can reproduce this consistently by using the steps below. I have tried it on both the blank and luma themes without success.

**Steps to reproduce.** 

1. Install Magento 2.2.3 EE out of the box. 
2. Add a configurable Product with simple both with images.
3. Go to the single product page and trying switching a variation.
4. You will see the thumbnails do not change. 

**Magento Version**
2.2.3 EE

**PHP Version**
7.1.17

**MySQL Version**
5.7.21

![example](https://user-images.githubusercontent.com/28379822/44058213-1b13deec-9f13-11e8-8624-9231a4b4def1.png)

**Comment by chattertech** [comment]
Similarly here... a png (main image) is layered over the secondary image... (also note image description showing)

![screen shot 2018-08-13 at 10 54 30 pm](https://user-images.githubusercontent.com/38303191/44074042-eba93b0a-9f4b-11e8-965f-3e5fe538ed64.jpg)

![screen shot 2018-08-13 at 10 54 48 pm](https://user-images.githubusercontent.com/38303191/44074050-f1f0580e-9f4b-11e8-8dd9-ab98159cc609.jpg)

**Comment by iroken222** [comment]
The issue with the thumbnails has to do with 
`frame.append(document.getElementById('fast-loder-'+i));` 
in the fotorama.js file on line 2496.

It reloads the default thumbnails that come in from the original load rather than grabbing new ones based on the dataFrame.
My temporary code is below to fix this. This is a workaround and is just to get it working on 2.2.3. 
**FIND:** frame.append(document.getElementById('fast-loder-'+i));
**REPLACE:** 
`frame.innerHTML = '<div class="fotorama__thumb fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img" id="fast-loder-' + i + '"><img src="' + dataFrame['thumb'] + '" alt="' + dataFrame['caption'] + '" class="fotorama__img" aria-hidden="false"></div>';`

**Comment by PiroozMB** [comment]
Hi @iroken222  I did what you mentioned. I removed this line from xumulus extension in fotorama.js:
    frame.append(document.getElementById('fast-loder-'+i));
and place this in it's place: frame.innerHTML = '<div class="fotorama__thumb fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img" id="fast-loder-' + i + '"><img src="' + dataFrame['thumb'] + '" alt="' + dataFrame['caption'] + '" class="fotorama__img" aria-hidden="false"></div>';
then i flushed the cache and static files. but still seeing no change and the issue is still there. Am I doing it in the way you mentioned correctly? Thanks.

**Comment by chattertech** [comment]
I have also just tried this fix and it does not fix the issue.

**Comment by dankoz51** [comment]
Fix in latest commit, fototrama changes fixed

**Comment by chattertech** [comment]
Thanks Dankoz

**Comment by dankoz51** [comment]
This has been fixed by reverting fotrama changes
