### ISSUE TITLE
GitHub Error in Extensions Manager

### ISSUE THREAD

**Issue by chattertech** [xumulus/magento2-fast-product-images#6]
Magento 2.2.3, PHP 7.026, MYSQL 5.6.35-80.0

I have installed this module using Composer as suggested. However when i try and access the extension manager i cannot use the extension manager.

I get the following error.

Command "show" failed: [RuntimeException] Failed to execute git clone --mirror 'git@github.com:xumulus/magento2-fast-product-images.git' '/home/pond/public_html/var/composer_home/cache/vcs/git-github.com-xumulus-magento2-fast-product-images.git/' show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>]

![screen shot 2018-08-13 at 6 02 25 pm](https://user-images.githubusercontent.com/38303191/44066063-303ccce2-9f23-11e8-95bc-1e313251a0b6.jpg)

**Comment by chattertech** [comment]
I think the issue was caused when i mistakenly put in the wrong token when installing. I removed the module via composer and installed via upload. I manually removed the entry in composer.json to fix the error.

Not really a fix but i don't think the issue was caused by the module per se.

**Comment by prodev903** [comment]
@chattertech 

How are you?
I met same issue. Could you explain me more details how to fix.

Kind Regards
